name: render

on:
  workflow_run:
    workflows: ["Build and push container image"]
    types:
      - completed
      
# This job installs dependencies, build the jupyter notebook, and pushes it to `render`, a new `branch`
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        # Set notebook anme
      - name: Get properties from the config file
        id: config_file
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'config.json'
          prop_path: 'notebook_name'
      # Render the notebook
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: quay.io/environmental_ds_book/test2i2c:latest
            options: --user root -v ${{ github.workspace }}:/tmp
            shell: bash
            run: |
                jupyter-nbconvert --to notebook --ExecutePreprocessor.kernel_name=python3 --inplace --execute ${{steps.config_file.outputs.prop}}
                cp ${{steps.config_file.outputs.prop}}  /tmp
      - name: Commit
        run: |
          ls
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rm \* ':!${{steps.config_file.outputs.prop}}'
          git add ${{steps.config_file.outputs.prop}}
          git commit -m 'update'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: render
         force: true
